---
- hosts: localhost
  vars_files:
    - "config/aws/secure_vars.yml"
    - "config/aws/global.yml"
#    - "config/{{vpc}}/services/{{service}}.yml"
    - "config/{{vpc_name}}/vpc.yml"

  roles:
    - create_instance