vpc:
  cidr_block: 172.16.0.0/16
  tenancy: default
  nat_gateway_subnet_name: public-1
  subnets:
  - availability_zone: us-east-1a
    cidr_block: 172.16.0.0/24
    name: public-1
    gateway: igw
  - availability_zone: us-east-1a
    cidr_block: 172.16.1.0/24
    name: private-1
    gateway: nat
  - availability_zone: us-east-1a
    cidr_block: 172.16.2.0/24
    name: private-2
